/******************************************************************************/
/***          Generated by IBExpert 2012.02.21 13/06/2025 08:11:41          ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES UTF8;

SET CLIENTLIB 'C:\Users\Luccas\Desktop\Viasoft\Src\AppVendas\XE7\db\fbclient.dll';

CREATE DATABASE 'C:\Users\Luccas\Desktop\Viasoft\Src\AppVendas\XE7\Release\Banco.FDB'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET UTF8 COLLATION UTF8;



/******************************************************************************/
/***                               Generators                               ***/
/******************************************************************************/

CREATE GENERATOR GEN_PRODUTO_ID;
SET GENERATOR GEN_PRODUTO_ID TO 30;

CREATE GENERATOR GEN_VENDA_ID;
SET GENERATOR GEN_VENDA_ID TO 15;

CREATE GENERATOR GEN_VENDA_ITEM_ID;
SET GENERATOR GEN_VENDA_ITEM_ID TO 0;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE PRODUTO (
    CODIGO_PRODUTO     INTEGER NOT NULL,
    NOME_PRODUTO       VARCHAR(100) NOT NULL,
    DESCRICAO_PRODUTO  VARCHAR(255),
    PRECO_PRODUTO      DECIMAL(10,2) NOT NULL
);

CREATE TABLE VENDA (
    CODIGO_VENDA        INTEGER NOT NULL,
    DATA_VENDA          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    NOME_CLIENTE_VENDA  VARCHAR(100) NOT NULL,
    CEP                 VARCHAR(10),
    ENDERECO_RUA        VARCHAR(100),
    ENDERECO_NUMERO     VARCHAR(10),
    ENDERECO_BAIRRO     VARCHAR(50),
    ENDERECO_CIDADE     VARCHAR(50),
    ENDERECO_ESTADO     VARCHAR(3),
    VALOR_TOTAL_VENDA   DECIMAL(12,2)
);



/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE PRODUTO ADD PRIMARY KEY (CODIGO_PRODUTO);
ALTER TABLE VENDA ADD PRIMARY KEY (CODIGO_VENDA);


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/


SET TERM ^ ;



/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/



/* Trigger: BI_PRODUTO_ID */
CREATE TRIGGER BI_PRODUTO_ID FOR PRODUTO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.CODIGO_PRODUTO IS NULL) THEN
    NEW.CODIGO_PRODUTO = GEN_ID(GEN_PRODUTO_ID, 1);
END
^

/* Trigger: BI_VENDA_ID */
CREATE TRIGGER BI_VENDA_ID FOR VENDA
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.CODIGO_VENDA IS NULL) THEN
    NEW.CODIGO_VENDA = GEN_ID(GEN_VENDA_ID, 1);
END
^

SET TERM ; ^

